#!/usr/bin/env python3
"""
GigaCheck Skill — AI vs Human Text Detection

Classifies whether English or Russian text was written by a human or generated by AI.
Uses GigaCheck-Classifier-Multi (Mistral-7B) via the Transformers API (trust_remote_code=True).

Pipeline:
  1. Detect language (only EN and RU are supported)
  2. Truncate text to first model.config.max_length tokens
  3. Run GigaCheck-Classifier-Multi for binary classification: AI / human
  4. Output structured JSON

Model:
  - https://huggingface.co/iitolstykh/GigaCheck-Classifier-Multi
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import torch
from langdetect import detect as detect_language
from langdetect.lang_detect_exception import LangDetectException
from transformers import AutoModel, AutoTokenizer

# ── Constants ──────────────────────────────────────────────────────────────────

MODEL_ID = "iitolstykh/GigaCheck-Classifier-Multi"
SUPPORTED_LANGUAGES = {"en", "ru"}


# ── Model loading ──────────────────────────────────────────────────────────────

def load_model(device: str):
    """Load GigaCheck model and tokenizer via Transformers API."""
    print(f"Loading GigaCheck model {MODEL_ID}...", file=sys.stderr)
    dtype = torch.bfloat16 if device == "cuda" else torch.float32
    model = AutoModel.from_pretrained(
        MODEL_ID,
        trust_remote_code=True,
        torch_dtype=dtype,
        device_map=device,
    )
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
    model.eval()
    max_tokens = getattr(model.config, "max_length", 1024)
    print(f"✅ Model loaded. Max sequence length: {max_tokens} tokens.", file=sys.stderr)
    return model, tokenizer, max_tokens


# ── Language detection ─────────────────────────────────────────────────────────

def detect_lang(text: str) -> str | None:
    """
    Detect text language. Returns ISO 639-1 code (e.g. 'en', 'ru').
    Returns None if detection fails.
    """
    try:
        return detect_language(text)
    except LangDetectException:
        return None


def check_language(text: str) -> str:
    """
    Validate that text is English or Russian.
    Returns the detected language code.
    Exits with error if unsupported language detected.
    """
    lang = detect_lang(text)
    if lang is None:
        error = {
            "error": "language_detection_failed",
            "message": "Could not detect text language. Provide at least a few sentences.",
        }
        print(json.dumps(error, ensure_ascii=False), flush=True)
        sys.exit(1)

    if lang not in SUPPORTED_LANGUAGES:
        error = {
            "error": "unsupported_language",
            "detected_language": lang,
            "message": (
                f"Detected language '{lang}' is not supported. "
                "GigaCheck-Classifier-Multi only supports English ('en') and Russian ('ru')."
            ),
        }
        print(json.dumps(error, ensure_ascii=False), flush=True)
        sys.exit(1)

    return lang


# ── Text preprocessing ─────────────────────────────────────────────────────────

def truncate_to_tokens(text: str, tokenizer, max_tokens: int) -> tuple[str, int]:
    """
    Truncate text to at most max_tokens tokens.
    Returns (truncated_text, actual_token_count).
    """
    tokens = tokenizer.encode(text, add_special_tokens=False)
    truncated_tokens = tokens[:max_tokens]
    truncated_text = tokenizer.decode(truncated_tokens, skip_special_tokens=True)
    return truncated_text, len(truncated_tokens)


# ── Inference ──────────────────────────────────────────────────────────────────

def classify_text(model, tokenizer, text: str, max_tokens: int) -> tuple[str, float, int]:
    """
    Run GigaCheck classification on a single text.
    Returns (label, confidence, tokens_used).
    label is one of: 'AI', 'human'
    """
    # Normalize newlines as per model recommendation
    normalized = text.replace("\n", " ")

    # Truncate to model's max_length tokens
    truncated, tokens_used = truncate_to_tokens(normalized, tokenizer, max_tokens)

    with torch.no_grad():
        output = model([truncated])

    # output.pred_label_ids: tensor of predicted label indices
    label_id = int(output.pred_label_ids[0])
    label = model.config.id2label[label_id]

    # Extract confidence if probabilities are available
    confidence = None
    if hasattr(output, "pred_probs") and output.pred_probs is not None:
        probs = output.pred_probs[0]
        confidence = round(float(probs.max().item()), 4)
    elif hasattr(output, "logits") and output.logits is not None:
        import torch.nn.functional as F
        probs = F.softmax(output.logits[0], dim=-1)
        confidence = round(float(probs.max().item()), 4)

    return label, confidence, tokens_used


# ── Single text pipeline ───────────────────────────────────────────────────────

def process_text(model, tokenizer, text: str, max_tokens: int) -> dict:
    """Full pipeline for a single text string."""
    lang = check_language(text)
    label, confidence, tokens_used = classify_text(model, tokenizer, text, max_tokens)

    result = {
        "label": label,
        "confidence": confidence,
        "language": lang,
        "tokens_used": tokens_used,
    }
    print(f"  → {label} (confidence={confidence}, lang={lang}, tokens={tokens_used})", file=sys.stderr)
    return result


def process_file(model, tokenizer, file_path: str, max_tokens: int) -> dict:
    """Read a text file and classify it."""
    path = Path(file_path)
    if not path.is_file():
        print(f"Error: file '{file_path}' not found.", file=sys.stderr)
        sys.exit(1)

    text = path.read_text(encoding="utf-8")
    if not text.strip():
        error = {"error": "empty_file", "message": f"File '{file_path}' is empty."}
        print(json.dumps(error, ensure_ascii=False), flush=True)
        sys.exit(1)

    print(f"Processing file: {path.name}", file=sys.stderr)
    return process_text(model, tokenizer, text, max_tokens)


def process_folder(model, tokenizer, folder_path: str, max_tokens: int) -> dict:
    """Classify all .txt files in a folder."""
    folder = Path(folder_path)
    if not folder.is_dir():
        print(f"Error: folder '{folder_path}' not found.", file=sys.stderr)
        sys.exit(1)

    txt_files = sorted(folder.glob("*.txt"))
    if not txt_files:
        print(f"No .txt files found in '{folder_path}'.", file=sys.stderr)
        sys.exit(1)

    results = {}
    for txt_file in txt_files:
        print(f"Processing {txt_file.name}...", file=sys.stderr)
        text = txt_file.read_text(encoding="utf-8")
        if not text.strip():
            results[txt_file.name] = {"error": "empty_file"}
            continue
        lang = detect_lang(text)
        if lang not in SUPPORTED_LANGUAGES:
            results[txt_file.name] = {
                "error": "unsupported_language",
                "detected_language": lang,
            }
            print(f"  ⚠️ Skipped: unsupported language '{lang}'", file=sys.stderr)
            continue
        label, confidence, tokens_used = classify_text(model, tokenizer, text, max_tokens)
        results[txt_file.name] = {
            "label": label,
            "confidence": confidence,
            "language": lang,
            "tokens_used": tokens_used,
        }
        print(f"  → {label} (confidence={confidence}, lang={lang}, tokens={tokens_used})", file=sys.stderr)

    return results


# ── Entry point ────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="GigaCheck — AI vs Human Text Detection Skill"
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--text", help="Raw text string to classify")
    group.add_argument("--file", help="Path to a .txt file to classify")
    group.add_argument("--folder", help="Path to a folder with .txt files (batch mode)")
    parser.add_argument(
        "--device",
        default="cuda" if torch.cuda.is_available() else "cpu",
        help="Device: cuda or cpu (default: auto-detect)",
    )
    args = parser.parse_args()

    model, tokenizer, max_tokens = load_model(args.device)

    if args.text:
        result = process_text(model, tokenizer, args.text, max_tokens)
        print(json.dumps(result, ensure_ascii=False, indent=2))

    elif args.file:
        result = process_file(model, tokenizer, args.file, max_tokens)
        print(json.dumps(result, ensure_ascii=False, indent=2))

    elif args.folder:
        results = process_folder(model, tokenizer, args.folder, max_tokens)
        print(json.dumps(results, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
